#define HH__BankRules_Section	8
#define HH__General_Section	9
#define HH__General_Section_ApplicationHomePage	10
#define HH__General_Section_AutoBrowse	11
#define HH__General_Section_BookDateMode	12
#define HH__General_Section_CompressSpaces	13
#define HH__General_Section_LogFile	14
#define HH__General_Section_MemoDelimiter	15
#define HH__General_Section_OutputFileType	16
#define HH__General_Section_PayeeCase	17
#define HH__General_Section_PromptForOutput	18
#define HH__General_Section_ScriptTimeout	19
#define HH__General_Section_StartImportAfterConversion	20
#define HH__General_Section_TxnDumpFile	21
#define HH__QIF_Section	22
#define HH__SpecialPayeeNames_Section	23
#define HH__Text_Extensions_Section	24
#define HH__Text_Section	25
#define HH__TxnTypeMap_Section	26
#define HH_Application_Object	27
#define HH_Balance_Object	28
#define HH_Bank_Specific_Configuration	29
#define HH_BankConfig_Object	30
#define HH_CSV_and_Text_Input	31
#define HH_How_scripts_are_invoked	32
#define HH_MT2OFX_Main_Window	33
#define HH_MT2OFX_INI	34
#define HH_MT940_Bank_Options_Window	35
#define HH_MT940_Matching_Window	36
#define HH_New_Bank_Window	37
#define HH_NonSwiftInfo_Object	39
#define HH_Object_Model	40
#define HH_Options_Window	41
#define HH_Options_Window_Book_Date	42
#define HH_Options_Window_Compress_multiple_spaces_in_payee_and_memo	43
#define HH_Options_Window_DecimalSeparator	44
#define HH_Options_Window_MemoDelimiter	45
#define HH_Options_Window_MT940_File_Extensions	46
#define HH_Options_Window_OutputFileType	47
#define HH_Options_Window_PayeeCase	48
#define HH_Options_Window_QIF_DateFormat	50
#define HH_Options_Window_Script_Editor	51
#define HH_Options_Window_Show_Open_Dialog_on_startup	52
#define HH_Options_Window_Start_import_after_conversion	53
#define HH_Options_Window_Text_File_Extensions	54
#define HH_Payee_Mapping_Window	55
#define HH_PayeeMap_Object	56
#define HH_PayeeMapItem_Object	57
#define HH_ProgramConfig_Object	58
#define HH_QIF_Output	59
#define HH_Regular_Expression_Syntax	60
#define HH_Scripting	61
#define HH_Session_Object	62
#define HH_Statement_Object	63
#define HH_Statements_Collection	64
#define HH_Str86Fields_Enum	65
#define HH_Str86Info_Object	66
#define HH_StructuredField_Object	67
#define HH_StructuredFields_Collection	68
#define HH_Supporting_a_New_Bank	69
#define HH_Text_Handling_Functions	70
#define HH_Text_Handling_Functions_AtEOF	71
#define HH_Text_Handling_Functions_NewStatement	72
#define HH_Text_Handling_Functions_NewTransaction	73
#define HH_Text_Handling_Functions_ParseLineDelimited	74
#define HH_Text_Handling_Functions_ParseLineFixed	75
#define HH_Text_Handling_Functions_ParseNumber	76
#define HH_Text_Handling_Functions_ReadLine	77
#define HH_Text_Input_Auto_Recognition_Window	78
#define HH_Text_Input_File_Extensions_Window	79
#define HH_Text_Input_Scripts	80
#define HH_Text_Input_Scripts_ConcatMemo	81
#define HH_Text_Input_Scripts_ParseDate	82
#define HH_Txn_Object	83
#define HH_Txns_Collection	84
#define HH_Utility_Functions	85
#define HH_Version_History	86
#define HH_Welcome_to_MT2OFX	87
#define HH_Options_Window_Save_output	49
